# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Home.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from login import qApp
from kepkel import Ui_DataKepKel
from iuran import Ui_Iuran
from laporan import Ui_Laporan
from PyQt5 import QtCore , QtGui, QtWidgets

class Ui_Home(object):

    def opendatakepkel(self):
        self.form = datakepkel()
        self.form.show() 

    def openiuran(self):
        self.form = iuran()
        self.form.show()

    def openlaporan(self):
        self.form = laporan()
        self.form.show()

    def cancel(self):
        qApp.exit(888)

    def setupUi(self, Home):
        Home.setObjectName("Home")
        Home.resize(600, 400)
        Home.setWindowFlags(QtCore.Qt.FramelessWindowHint)
        Home.setAttribute(QtCore.Qt.WA_TranslucentBackground)
        self.centralwidget = QtWidgets.QWidget(Home)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(110, 20, 371, 91))
        self.label.setStyleSheet("font: 75 24pt \"Poppins\" ; color:white")
        self.label.setObjectName("label")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(0, 0, 600, 400))
        self.widget.setStyleSheet("background-color: #2A3C44;\n"
"border-radius:10px;")
        self.widget.setObjectName("widget")
        self.btnKepKel = QtWidgets.QPushButton(self.widget)
        self.btnKepKel.setGeometry(QtCore.QRect(90, 150, 160, 70))
        self.btnKepKel.setStyleSheet("font: 75 11pt \"Poppins\";color:white;\n"
"background-color:#475A63;\n"
"border:1px #475A63;\n"
"border-radius:5px")
        self.btnKepKel.setObjectName("btnKepKel")
        self.btnKepKel.clicked.connect(self.opendatakepkel)

        self.btnIuran = QtWidgets.QPushButton(self.widget)
        self.btnIuran.setGeometry(QtCore.QRect(350, 150, 160, 70))
        self.btnIuran.setStyleSheet("font: 75 11pt \"Poppins\";color:white;\n"
"background-color:#475A63;\n"
"border:1px #475A63;\n"
"border-radius:5px")
        self.btnIuran.setObjectName("btnIuran")
        self.btnIuran.clicked.connect(self.openiuran)

        self.btnLap = QtWidgets.QPushButton(self.widget)
        self.btnLap.setGeometry(QtCore.QRect(90, 260, 160, 70))
        self.btnLap.setStyleSheet("font: 75 11pt \"Poppins\";color:white;\n"
"background-color:#475A63;\n"
"border:1px #475A63;\n"
"border-radius:5px")
        self.btnLap.setObjectName("btnLap")
        self.btnLap.clicked.connect(self.openlaporan)

        self.btnLogout = QtWidgets.QPushButton(self.widget)
        self.btnLogout.setGeometry(QtCore.QRect(350, 260, 160, 70))
        self.btnLogout.setStyleSheet("font: 75 11pt \"Poppins\";color:white;\n"
"background-color:#475A63;\n"
"border:1px #475A63;\n"
"border-radius:5px")
        self.btnLogout.setObjectName("btnLogout")
        self.btnLogout.clicked.connect(self.cancel)

        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setGeometry(QtCore.QRect(0, 0, 601, 401))
        self.label_2.setStyleSheet("border-radius:50px;")
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("Source Code/Background.png"))
        self.label_2.setObjectName("label_2")
        self.label_2.raise_()
        self.btnKepKel.raise_()
        self.btnIuran.raise_()
        self.btnLap.raise_()
        self.btnLogout.raise_()
        self.widget.raise_()
        self.label.raise_()
        Home.setCentralWidget(self.centralwidget)

        self.retranslateUi(Home)
        QtCore.QMetaObject.connectSlotsByName(Home)

    def retranslateUi(self, Home):
        _translate = QtCore.QCoreApplication.translate
        Home.setWindowTitle(_translate("Home", "MainWindow"))
        self.label.setText(_translate("Home", "Sistem Informasi RT 01"))
        self.btnKepKel.setWhatsThis(_translate("Home", "<html><head/><body><p><br/></p></body></html>"))
        self.btnKepKel.setText(_translate("Home", "Data Kepala\n"
"Keluarga"))
        self.btnIuran.setWhatsThis(_translate("Home", "<html><head/><body><p><br/></p></body></html>"))
        self.btnIuran.setText(_translate("Home", "Iuran"))
        self.btnLap.setWhatsThis(_translate("Home", "<html><head/><body><p><br/></p></body></html>"))
        self.btnLap.setText(_translate("Home", "Laporan\n"
"Keuangan"))
        self.btnLogout.setWhatsThis(_translate("Home", "<html><head/><body><p><br/></p></body></html>"))
        self.btnLogout.setText(_translate("Home", "Keluar"))

class datakepkel(QtWidgets.QMainWindow, Ui_DataKepKel):
    def __init__(self):
        super().__init__()
        self.home = Ui_DataKepKel()
        self.home.setupUi(self)
        self.show()

class iuran(QtWidgets.QMainWindow, Ui_Iuran):
    def __init__(self):
        super().__init__()
        self.home = Ui_Iuran()
        self.home.setupUi(self)
        self.show()

class laporan(QtWidgets.QMainWindow, Ui_Laporan):
    def __init__(self):
        super().__init__()
        self.home = Ui_Laporan()
        self.home.setupUi(self)
        self.show()

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Home = QtWidgets.QMainWindow()
    ui = Ui_Home()
    ui.setupUi(Home)
    Home.show()
    sys.exit(app.exec_())
