# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'KepKel.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QDesktopWidget,QWidget,QApplication
import pymysql


class Ui_DataKepKel(object):

    def loaddata(self):
        conn = pymysql.connect(host="localhost",user="root",password="", db="db_sisfo")
        cur = conn.cursor()
        result = cur.execute("SELECT * FROM tb_datakepalakeluarga")

        self.tableWidget.setRowCount(0)
        
        for row_number, row_data in enumerate(cur):
            self.tableWidget.insertRow(row_number)
            for column_number, data in enumerate(row_data):
                self.tableWidget.setItem(row_number, column_number, QtWidgets.QTableWidgetItem(str(data)))


    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1063, 680)
        MainWindow.setWindowFlags(QtCore.Qt.FramelessWindowHint)
        MainWindow.setAttribute(QtCore.Qt.WA_TranslucentBackground)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(30, 30, 391, 601))
        self.widget.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(71, 90, 99, 255), stop:1 rgba(42, 60, 68, 255));\n"
"border-radius:10px;")
        self.widget.setObjectName("widget")
        self.txtId = QtWidgets.QLineEdit(self.widget)
        self.txtId.setGeometry(QtCore.QRect(30, 120, 331, 31))
        self.txtId.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"border:2px solid rgba(0,0,0,0);\n"
"border-radius:1px;\n"
"border-bottom-color:rgb(255, 255, 255);\n"
"color:rgb(0,0,0);\n"
"padding-bottom:7px;\n"
"font: 57 12pt \"Poppins Medium\";color:rgb(255, 255, 255);")
        self.txtId.setPlaceholderText("")
        self.txtId.setObjectName("txtId")
        self.txtNama = QtWidgets.QLineEdit(self.widget)
        self.txtNama.setGeometry(QtCore.QRect(30, 210, 331, 31))
        self.txtNama.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"border:2px solid rgba(0,0,0,0);\n"
"border-radius:1px;\n"
"border-bottom-color:rgb(255, 255, 255);\n"
"color:rgb(0,0,0);\n"
"padding-bottom:7px;\n"
"font: 57 12pt \"Poppins Medium\";color:rgb(255, 255, 255);")
        self.txtNama.setPlaceholderText("")
        self.txtNama.setObjectName("txtNama")
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setGeometry(QtCore.QRect(100, 20, 191, 61))
        self.label_3.setStyleSheet("font: 75 20pt \"Poppins\"; color:white;\n"
"background-color:transparent\n"
"")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.widget)
        self.label_4.setGeometry(QtCore.QRect(30, 180, 71, 31))
        self.label_4.setStyleSheet("font: 75 13pt \"Poppins Medium\"; color:white;\n"
"background-color:transparent\n"
"")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.widget)
        self.label_5.setGeometry(QtCore.QRect(30, 270, 101, 31))
        self.label_5.setStyleSheet("font: 75 13pt \"Poppins Medium\"; color:white;\n"
"background-color:transparent\n"
"")
        self.label_5.setObjectName("label_5")
        self.txtNoRumah = QtWidgets.QLineEdit(self.widget)
        self.txtNoRumah.setGeometry(QtCore.QRect(30, 310, 331, 31))
        self.txtNoRumah.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"border:2px solid rgba(0,0,0,0);\n"
"border-radius:1px;\n"
"border-bottom-color:rgb(255, 255, 255);\n"
"color:rgb(0,0,0);\n"
"padding-bottom:7px;\n"
"font: 57 12pt \"Poppins Medium\";color:rgb(255, 255, 255);")
        self.txtNoRumah.setPlaceholderText("")
        self.txtNoRumah.setObjectName("txtNoRumah")
        self.label_6 = QtWidgets.QLabel(self.widget)
        self.label_6.setGeometry(QtCore.QRect(30, 370, 101, 31))
        self.label_6.setStyleSheet("font: 75 13pt \"Poppins Medium\"; color:white;\n"
"background-color:transparent\n"
"")
        self.label_6.setObjectName("label_6")
        self.txtNoTelp = QtWidgets.QLineEdit(self.widget)
        self.txtNoTelp.setGeometry(QtCore.QRect(30, 410, 331, 31))
        self.txtNoTelp.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"border:2px solid rgba(0,0,0,0);\n"
"border-radius:1px;\n"
"border-bottom-color:rgb(255, 255, 255);\n"
"color:rgb(0,0,0);\n"
"padding-bottom:7px;\n"
"font: 57 12pt \"Poppins Medium\";color:rgb(255, 255, 255);")
        self.txtNoTelp.setPlaceholderText("")
        self.txtNoTelp.setObjectName("txtNoTelp")
        self.label_7 = QtWidgets.QLabel(self.widget)
        self.label_7.setGeometry(QtCore.QRect(30, 90, 71, 31))
        self.label_7.setStyleSheet("font: 75 13pt \"Poppins Medium\"; color:white;\n"
"background-color:transparent\n"
"")
        self.label_7.setObjectName("label_7")
        self.btnTambah = QtWidgets.QPushButton(self.widget)
        self.btnTambah.setGeometry(QtCore.QRect(20, 470, 111, 40))
        self.btnTambah.setStyleSheet("font: 75 13pt \"Poppins\";color:white;\n"
"background-color:#009AFF;\n"
"border-radius:5px;\n"
"\n"
"")
        self.btnTambah.setObjectName("btnTambah")
        self.btnTambah.clicked.connect(self.tambah)

        self.btnHapus = QtWidgets.QPushButton(self.widget)
        self.btnHapus.setGeometry(QtCore.QRect(260, 470, 111, 40))
        self.btnHapus.setStyleSheet("font: 75 13pt \"Poppins\";color:white;\n"
"background-color:#009AFF;\n"
"border-radius:5px;\n"
"\n"
"")
        self.btnHapus.setObjectName("btnHapus")
        self.btnHapus.clicked.connect(self.hapus)

        self.btnEdit = QtWidgets.QPushButton(self.widget)
        self.btnEdit.setGeometry(QtCore.QRect(140, 470, 111, 40))
        self.btnEdit.setStyleSheet("font: 75 13pt \"Poppins\";color:white;\n"
"background-color:#009AFF;\n"
"border-radius:5px;\n"
"\n"
"")
        self.btnEdit.setObjectName("btnEdit")
        self.btnEdit.clicked.connect(self.edit)


        self.btnClear = QtWidgets.QPushButton(self.widget)
        self.btnClear.setGeometry(QtCore.QRect(80, 530, 111, 40))
        self.btnClear.setStyleSheet("font: 75 13pt \"Poppins\";color:white;\n"
"background-color:#009AFF;\n"
"border-radius:5px;\n"
"\n"
"")
        self.btnClear.setObjectName("btnClear")
        self.btnClear.clicked.connect(self.clear)

        self.btnKembali = QtWidgets.QPushButton(self.widget)
        self.btnKembali.setGeometry(QtCore.QRect(200, 530, 111, 40))
        self.btnKembali.setStyleSheet("font: 75 13pt \"Poppins\";color:white;\n"
"background-color:#009AFF;\n"
"border-radius:5px;\n"
"\n"
"")
        self.btnKembali.setObjectName("btnKembali")
        self.btnKembali.clicked.connect(MainWindow.close)

        self.widget_2 = QtWidgets.QWidget(self.centralwidget)
        self.widget_2.setGeometry(QtCore.QRect(390, 70, 631, 521))
        self.widget_2.setStyleSheet("background-color: #2A3C44;\n"
"border-radius:10px;")
        self.widget_2.setObjectName("widget_2")
        self.tableWidget = QtWidgets.QTableWidget(self.widget_2)
        self.tableWidget.setGeometry(QtCore.QRect(60, 110, 541, 251))
        self.tableWidget.setStyleSheet("QHeaderView::section {                          \n"
"    color: white;                               \n"
"    padding: 2px;                               \n"
"    height:20px;                                \n"
"    border: 0px solid #567dbc;                  \n"
"    font: 75 10pt \"Poppins\"; color:white;     \n"
"    border-left:0px;                            \n"
"    border-right:0px;                           \n"
"    background-color: #475A63;                        \n"
"}\n"
"\n"
"QTableWidget{ \n"
"    background-color:#475A63;\n"
"    font: 75 10pt \"Poppins Medium\"; color:white;"
"}\n"
"")
        self.tableWidget.setRowCount(0)
        self.tableWidget.setColumnCount(4)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.verticalHeader().setVisible(False)
        self.tableWidget.setHorizontalHeaderLabels(('Id', 'Nama', 'No Rumah', 'No Telp'))
        self.tableWidget.setColumnWidth(0,50)
        self.tableWidget.setColumnWidth(1,200)
        self.tableWidget.setColumnWidth(2,100)
        self.tableWidget.setColumnWidth(3,191.5)
        self.tableWidget.setEditTriggers(QtWidgets.QTableWidget.NoEditTriggers)
        self.tableWidget.itemClicked.connect(self.gett)
        self.loaddata()

        self.label_8 = QtWidgets.QLabel(self.widget_2)
        self.label_8.setGeometry(QtCore.QRect(170, 30, 311, 61))
        self.label_8.setStyleSheet("font: 75 20pt \"Poppins\"; color:white;\n""background-color:transparent\n""")
        self.label_8.setObjectName("label_8")
        self.widget_2.raise_()
        self.widget.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_3.setText(_translate("MainWindow", "Tambah Data"))
        self.label_4.setText(_translate("MainWindow", "Nama : "))
        self.label_5.setText(_translate("MainWindow", "No Rumah :"))
        self.label_6.setText(_translate("MainWindow", "No Telp :"))
        self.label_7.setText(_translate("MainWindow", "Id :"))
        self.btnTambah.setText(_translate("MainWindow", "Tambah"))
        self.btnHapus.setText(_translate("MainWindow", "Hapus"))
        self.btnEdit.setText(_translate("MainWindow", "Edit"))
        self.btnClear.setText(_translate("MainWindow", "Clear"))
        self.btnKembali.setText(_translate("MainWindow", "Kembali"))
        self.label_8.setText(_translate("MainWindow", "Data Kepala Keluarga"))
    

    def gett(self):
        indexes = []
        for selectionRange in self.tableWidget.selectedRanges():
            indexes.extend(range(selectionRange.topRow(), selectionRange.bottomRow()+1))
        for i in indexes:
            self.txtId.setText(self.tableWidget.item(i, 0).text())
            self.txtId.setEnabled(False)
            self.txtNama.setText(self.tableWidget.item(i, 1).text())
            self.txtNoRumah.setText(self.tableWidget.item(i, 2).text())
            self.txtNoTelp.setText(self.tableWidget.item(i, 3).text())

            
    def tambah(self):
        id = self.txtId.text()
        nama = self.txtNama.text()
        noRumah = self.txtNoRumah.text()
        noTelp = self.txtNoTelp.text()
        insert = (id, nama, noRumah, noTelp)
        print(insert)
        if self.txtId.text() and self.txtNama.text() and self.txtNoRumah.text() and self.txtNoTelp.text():
            con = pymysql.connect(db='db_sisfo', user='root', passwd='', host='localhost', port=3306, autocommit=True)
            cur = con.cursor()
            sql = "INSERT INTO tb_datakepalakeluarga(id, nama, no_rumah, no_telp)" + "VALUES"+ str(insert)
            data = cur.execute(sql)
            self.messagebox("SUKSES", "Data Berhasil Ditambahkan")
            self.loaddata()
            self.clear()
        else:
            self.messagebox("GAGAL", "Mohon lengkapi Form ")
        
    
    def clear(self):
        self.txtId.clear()
        self.txtId.setEnabled(True)
        self.txtNama.clear()
        self.txtNoRumah.clear()
        self.txtNoTelp.clear()
    
    def messagebox(self,title,message):
        mess = QtWidgets.QMessageBox()
        mess.setWindowTitle(title)
        mess.setText(message)
        mess.setStandardButtons(QtWidgets.QMessageBox.Ok)
        mess.exec_()

    def edit(self):
        id = self.txtId.text()
        nama = self.txtNama.text()
        noRumah = self.txtNoRumah.text()
        noTelp = self.txtNoTelp.text()
        con = pymysql.connect(db='db_sisfo', user='root', passwd='', host='localhost', port=3306, autocommit=True)
        cur = con.cursor()
        sql = "UPDATE tb_datakepalakeluarga SET nama=%s, no_rumah=%s, no_telp=%s WHERE id=%s"
        data = cur.execute(sql, (nama, noRumah, noTelp, id))
        if (data):
            self.messagebox("SUKSES", "Data Berhasil Di Edit")
        else:
            self.messagebox("GAGAL", "Data Gagal Di Edit")
        self.loaddata()
        self.clear()

    def hapus(self):
        id = self.txtId.text()
        con = pymysql.connect(db='db_sisfo', user='root', passwd='', host='localhost', port=3306, autocommit=True)
        cur = con.cursor()
        sql = "DELETE FROM tb_datakepalakeluarga where id=%s"
        data = cur.execute(sql, (id))
        if (data):
            self.messagebox("SUKSES", "Data Berhasil Di Hapus")
        else:  
            self.messagebox("GAGAL", "Data Gagal Di Hapus")
        self.loaddata()
        self.clear()

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_DataKepKel()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
