# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Login.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


import sys
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import *
import pymysql
import pymysql.cursors
from home import *


class Ui_Login(object):
    def koneksi(self):
        conn = pymysql.connect(host="localhost",user="root",password="", db="db_sisfo")
        cur = conn.cursor()
        if(cur):
                self.messagebox("Koneksi", "Koneksi Database Berhasil")
        else:
                self.messagebox("Koneksi", "Koneksi Database Gagal")

    def messagebox(self,title,message):
        mess = QtWidgets.QMessageBox()
        mess.setWindowTitle(title)
        mess.setText(message)
        mess.setStandardButtons(QtWidgets.QMessageBox.Ok)
        mess.exec_()

    def warning(self,title,message):
        mess = QtWidgets.QMessageBox()
        mess.setWindowTitle(title)
        mess.setText(message)
        mess.setStandardButtons(QtWidgets.QMessageBox.Ok)
        mess.exec_()

    def openhome(self):
        self.form = home()
        self.form.show()        

    def login(self):
        username = self.uname.text()
        password = self.passwo.text()
        conn = pymysql.connect(host="localhost",user="root",password="", db="db_sisfo")
        cur = conn.cursor()
        query = 'Select * from tb_login where username=%s and password=%s'
        data = cur.execute(query, (username,password))
        if(len(cur.fetchall())>0):
                self.openhome()
                self.messagebox("Login Success","Anda Berhasil Login")
        else:
                self.warning("Login Failed","Username atau Password Salah")

    

    def setupUi(self, MainWindow):
        self.koneksi()
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(593, 492)
        MainWindow.setWindowFlags(QtCore.Qt.FramelessWindowHint)
        MainWindow.setAttribute(QtCore.Qt.WA_TranslucentBackground)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(40, 30, 241, 421))
        self.widget.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(71, 90, 99, 255), stop:1 rgba(42, 60, 68, 255));\n"
"border-radius:10px;")
        self.widget.setObjectName("widget")
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setGeometry(QtCore.QRect(30, 40, 181, 61))
        self.label_3.setStyleSheet("font: 75 16pt \"Poppins\"; color:white;\n"
"background-color:transparent\n"
"")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.widget)
        self.label_4.setGeometry(QtCore.QRect(30, 130, 181, 61))
        self.label_4.setStyleSheet("background-color:transparent;\n"
"font: 57 10pt \"Poppins Medium\";color:white;\n"
"")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.widget)
        self.label_5.setGeometry(QtCore.QRect(0, 290, 241, 151))
        font = QtGui.QFont()
        font.setFamily("Mountain")
        font.setPointSize(150)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("background-color:transparent;\n"
"color:rgb(83, 106, 116)\n"
"")
        self.label_5.setObjectName("label_5")
        self.widget_2 = QtWidgets.QWidget(self.centralwidget)
        self.widget_2.setGeometry(QtCore.QRect(270, 50, 281, 381))
        self.widget_2.setStyleSheet("background-color:white;\n"
"border-radius:10px;\n"
"\n"
"\n"
"\n"
"")
        self.widget_2.setObjectName("widget_2")
        self.label = QtWidgets.QLabel(self.widget_2)
        self.label.setGeometry(QtCore.QRect(90, 30, 121, 51))
        self.label.setStyleSheet("font: 75 26pt \"Poppins\"; color:#2A3C44\n"
"")
        self.label.setObjectName("label")
        self.uname = QtWidgets.QLineEdit(self.widget_2)
        self.uname.setGeometry(QtCore.QRect(40, 120, 201, 31))
        self.uname.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"border:2px solid rgba(0,0,0,0);\n"
"border-radius:1px;\n"
"border-bottom-color:rgba(46,82,101,200);\n"
"color:#475A63;\n"
"padding-bottom:7px;\n"
"font: 57 12pt \"Poppins Medium\";")
        self.uname.setObjectName("uname")
        self.passwo = QtWidgets.QLineEdit(self.widget_2)
        self.passwo.setGeometry(QtCore.QRect(40, 190, 201, 31))
        self.passwo.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"border:2px solid rgba(0,0,0,0);\n"
"border-radius:1px;\n"
"border-bottom-color:rgba(46,82,101,200);\n"
"color:#475A63;\n"
"padding-bottom:7px;\n"
"font: 57 12pt \"Poppins Medium\";")
        self.passwo.setEchoMode(QtWidgets.QLineEdit.Password)
        self.passwo.setObjectName("passwo")
        self.btnLogin = QtWidgets.QPushButton(self.widget_2)
        self.btnLogin.setGeometry(QtCore.QRect(40, 250, 201, 40))
        self.btnLogin.setStyleSheet("font: 75 13pt \"Poppins\";color:white;\n"
"background-color:#009AFF;\n"
"border-radius:5px;\n"
"\n"
"")
        self.btnLogin.setObjectName("btnLogin")
        self.btnLogin.clicked.connect(self.login)
        self.btnKeluar = QtWidgets.QPushButton(self.widget_2)
        self.btnKeluar.setGeometry(QtCore.QRect(40, 310, 201, 40))
        self.btnKeluar.setStyleSheet("font: 75 13pt \"Poppins\";color:white;\n"
"background-color:#009AFF;\n"
"border-radius:5px")
        self.btnKeluar.setObjectName("btnKeluar")
        self.btnKeluar.clicked.connect(MainWindow.close)
        self.widget_2.raise_()
        self.widget.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_3.setText(_translate("MainWindow", "Sistem Informasi\n"
"RT 01"))
        self.label_4.setText(_translate("MainWindow", "Halo\n"
"Selamat Datang di Aplikasi\n"
"Sistem Informasi RT 01"))
        self.label_5.setText(_translate("MainWindow", "­­­­-"))
        self.label.setText(_translate("MainWindow", "LOGIN"))
        self.uname.setPlaceholderText(_translate("MainWindow", "Username"))
        self.passwo.setPlaceholderText(_translate("MainWindow", "Password"))
        self.btnLogin.setText(_translate("MainWindow", "Login"))
        self.btnKeluar.setText(_translate("MainWindow", "Keluar"))

class home(QtWidgets.QMainWindow, Ui_Login):
    def __init__(self):
        super().__init__()
        self.home = Ui_Home()
        self.home.setupUi(self)
        self.show()
        MainWindow.close()

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_Login()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
